version: '3.9'

services:
  api:
    container_name: store-api
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
      - .env.docker
    depends_on:
      postgres-db:
        condition: service_healthy
    restart: always

  postgres-db:
    image: postgres:latest
    container_name: store-postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} --dbname ${POSTGRES_DB} --port ${POSTGRES_PORT}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    env_file:
      - .env
      - .env.docker
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}

volumes:
  pg_data: